Fix sphinx build and update link to sphinx docs
The rendered html `<img height="INT">` is implicitly pixels.
sphinx-build 2.4.4 threw when casting to int().

```
  File "/usr/local/lib/python3.7/site-packages/sphinx/writers/html5.py",
  line 550, in visit_image
      atts['height'] = int(atts['height']) * scale
      ValueError: invalid literal for int() with base 10: '265px'
```

The rendered php5 file had `<img height="500">` for 250px and 200%
scale. (The last svg was 81 pixels tall,
and I'm not familiar with why both height and scale are set)